# Site settings
title: Benjamin Congdon's Personal Website
name: Benjamin Congdon
email: bcongdo2@illinois.edu
description: > 
  The personal site of Benjamin Congdon.
baseurl: ""
url: "http://benjamincongdon.me"
blog_url: "blog"

twitter_username: BenRCongdon
github_username:  bcongdon
medium_username: bencongdon
500px_username: BenRCongdon
quora_username: Benjamin-Congdon-1
goodreads_username: benjamincongdon

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true
show_sharing_icons:   true

enable_mathjax: false
extended_fonts: false


# Build settings
markdown: kramdown
permalink:     /blog/:year/:month/:day/:title/
paginate:     5
paginate_path: 'blog/page:num'
future: true
sass:
  compressed: true
  sass_dir: css
  style:    expanded
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - rouge
  - jemoji
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: [README.md, vendor, script]
